### ISSUE TITLE
Code Review for Team 108(The Mambas)

### ISSUE THREAD

**Issue by ebeagusamuel** [Mikearaya/newsweek-clone#1]
- Nice work so far. Take your time in perfecting the project and add the necessary media queries.
- It is better to use hexadecimal colors as opposed to referencing the name of the color directly.
- Some of your CSS selectors are very long, try making them shorter.

**Comment by Mikearaya** [comment]
## thank you for your suggestions. I have: 
- changed colors to HEX
- simplified CSS selectors

# Closing this issue
